// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: message.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DouyinMessageServiceClient is the client API for DouyinMessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DouyinMessageServiceClient interface {
	CreateMessage(ctx context.Context, in *CreateMessageReq, opts ...grpc.CallOption) (*CreateMessageResp, error)
	GetMessageList(ctx context.Context, in *GetMessageListReq, opts ...grpc.CallOption) (*GetMessageListResp, error)
}

type douyinMessageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDouyinMessageServiceClient(cc grpc.ClientConnInterface) DouyinMessageServiceClient {
	return &douyinMessageServiceClient{cc}
}

func (c *douyinMessageServiceClient) CreateMessage(ctx context.Context, in *CreateMessageReq, opts ...grpc.CallOption) (*CreateMessageResp, error) {
	out := new(CreateMessageResp)
	err := c.cc.Invoke(ctx, "/message.DouyinMessageService/CreateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *douyinMessageServiceClient) GetMessageList(ctx context.Context, in *GetMessageListReq, opts ...grpc.CallOption) (*GetMessageListResp, error) {
	out := new(GetMessageListResp)
	err := c.cc.Invoke(ctx, "/message.DouyinMessageService/GetMessageList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DouyinMessageServiceServer is the server API for DouyinMessageService service.
// All implementations must embed UnimplementedDouyinMessageServiceServer
// for forward compatibility
type DouyinMessageServiceServer interface {
	CreateMessage(context.Context, *CreateMessageReq) (*CreateMessageResp, error)
	GetMessageList(context.Context, *GetMessageListReq) (*GetMessageListResp, error)
	mustEmbedUnimplementedDouyinMessageServiceServer()
}

// UnimplementedDouyinMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDouyinMessageServiceServer struct {
}

func (UnimplementedDouyinMessageServiceServer) CreateMessage(context.Context, *CreateMessageReq) (*CreateMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMessage not implemented")
}
func (UnimplementedDouyinMessageServiceServer) GetMessageList(context.Context, *GetMessageListReq) (*GetMessageListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessageList not implemented")
}
func (UnimplementedDouyinMessageServiceServer) mustEmbedUnimplementedDouyinMessageServiceServer() {}

// UnsafeDouyinMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DouyinMessageServiceServer will
// result in compilation errors.
type UnsafeDouyinMessageServiceServer interface {
	mustEmbedUnimplementedDouyinMessageServiceServer()
}

func RegisterDouyinMessageServiceServer(s grpc.ServiceRegistrar, srv DouyinMessageServiceServer) {
	s.RegisterService(&DouyinMessageService_ServiceDesc, srv)
}

func _DouyinMessageService_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DouyinMessageServiceServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.DouyinMessageService/CreateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DouyinMessageServiceServer).CreateMessage(ctx, req.(*CreateMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DouyinMessageService_GetMessageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DouyinMessageServiceServer).GetMessageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.DouyinMessageService/GetMessageList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DouyinMessageServiceServer).GetMessageList(ctx, req.(*GetMessageListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DouyinMessageService_ServiceDesc is the grpc.ServiceDesc for DouyinMessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DouyinMessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.DouyinMessageService",
	HandlerType: (*DouyinMessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMessage",
			Handler:    _DouyinMessageService_CreateMessage_Handler,
		},
		{
			MethodName: "GetMessageList",
			Handler:    _DouyinMessageService_GetMessageList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
